config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  resources :events do
    resources :registrations do
      member do
        get "steps/1" => "registrations#step1", :as => :step1
        patch "steps/1/update" => "registrations#step1_update", :as => :update_step1
        get "steps/2" => "registrations#step2", :as => :step2
        patch "steps/2/update" => "registrations#step2_update", :as => :update_step2
        get "steps/3" => "registrations#step3", :as => :step3
        patch "steps/3/update" => "registrations#step3_update", :as => :update_step3
      end
    end
  end

  namespace :admin do
    root "events#index"
    resources :events do
      resources :tickets, :controller => "event_tickets"
      resources :departments, :controller => "event_departments"
      resources :jobs, :controller => "event_jobs"
      resources :registrations, :controller => "event_registrations"
    end
    resources :users
    resources :groups
  end

  resource :user
end

app/models/event.rb
class Event < ApplicationRecord

  validates_presence_of :name

  before_validation :generate_friendly_id, :on => :create

  has_many :tickets, :dependent => :destroy
  has_many :departments, :dependent => :destroy
  has_many :jobs, :dependent => :destroy
  has_many :registrations, :dependent => :destroy


  def to_param
    self.friendly_id
  end

  protected

  def generate_friendly_id
    self.friendly_id ||= SecureRandom.uuid
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  layout "admin"

  def index
    @events = Event.all
  end

  def show
    @event = Event.find_by_friendly_id!(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to admin_events_path
    else
      render "new"
    end
  end

  def edit
    @event = Event.find_by_friendly_id!(params[:id])
  end

  def update
    @event = Event.find_by_friendly_id!(params[:id])

    if @event.update(event_params)
      redirect_to admin_events_path
    else
      render "edit"
    end
  end

  def destroy
    @event = Event.find_by_friendly_id!(params[:id])
    @event.destroy

    redirect_to admin_events_path
  end

  protected

  def event_params
    params.require(:event).permit(:name, :description)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find_by_friendly_id!(params[:id])
    @registrations = @event.registrations.includes(:ticket, :department, :job).order("id DESC").page(params[:page]).per(10)

    if Array(params[:statuses]).any?
      @registrations = @registrations.by_status(params[:statuses])
    end

    if Array(params[:ticket_ids]).any?
      @registrations = @registrations.by_ticket(params[:ticket_ids])
    end

    if Array(params[:job_ids]).any?
      @registrations = @registrations.by_job(params[:job_ids])
    end
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
  def registration_filters(options)
    params.permit(:status, :ticket_id, :department_id, :job_id).merge(options)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, :class => "form-control" %>
</div>

app/views/admin/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for [:admin, @event] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Update", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_events_path %>
  </div>
<% end %>

app/views/admin/events/index.html.erb
<h1>部门管理列表</h1>

<p class="text-right">
<%= link_to "新增部门", new_admin_event_path, :class => "btn btn-primary" %>
</p>

<table class="table">
    <thead>
      <tr>

        <th>部门名称</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>

          <td>

            <%= link_to event.name, admin_event_path(event) %>
          </td>
          <td>
            <%= link_to "日志管理", admin_event_registrations_path(event), :class => "btn btn-default" %>
            <%= link_to "业务", admin_event_tickets_path(event), :class => "btn btn-default" %>
            <%= link_to "用户单位", admin_event_departments_path(event), :class => "btn btn-default" %>
            <%= link_to "班组", admin_event_jobs_path(event), :class => "btn btn-default" %>
            <%= link_to "编辑", edit_admin_event_path(event), :class => "btn btn-default" %>
            <%= link_to "删除", admin_event_path(event), :method => "delete", :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger" %>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/admin/events/new.html.erb
<h1>New Event</h1>

<%= form_for [:admin, @event] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Create", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_events_path %>
  </div>
<% end %>

app/views/admin/events/show.html.erb
<h1><%= @event.name %></h1>

<p>
  <%= link_to "打開前台", event_path(@event), :target => "_blank", :class => "btn btn-primary" %>
</p>

<%= simple_format @event.description %>