config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  resources :events do
    resources :registrations do
      member do
        get "steps/1" => "registrations#step1", :as => :step1
        patch "steps/1/update" => "registrations#step1_update", :as => :update_step1
        get "steps/2" => "registrations#step2", :as => :step2
        patch "steps/2/update" => "registrations#step2_update", :as => :update_step2
        get "steps/3" => "registrations#step3", :as => :step3
        patch "steps/3/update" => "registrations#step3_update", :as => :update_step3
      end
    end
  end

  namespace :admin do
    root "events#index"
    resources :events do
      resources :tickets, :controller => "event_tickets"
      resources :departments, :controller => "event_departments"
      resources :jobs, :controller => "event_jobs"
      resources :registrations, :controller => "event_registrations"
    end
    resources :users
    resources :groups
  end

  resource :user
end

app/controllers/admin/event_tickets_controller.rb
class Admin::EventTicketsController < ApplicationController
  layout "admin"
  before_action :find_event

   def index
     @tickets = @event.tickets
   end

   def new
     @ticket = @event.tickets.new
   end

   def create
     @ticket = @event.tickets.new(ticket_params)
     if @ticket.save
       redirect_to admin_event_tickets_path(@event)
     else
       render "new"
     end
   end

   def edit
     @ticket = @event.tickets.find(params[:id])
   end

   def update
     @ticket = @event.tickets.find(params[:id])

     if @ticket.update(ticket_params)
       redirect_to admin_event_tickets_path(@event)
     else
       render "edit"
     end
   end

   def destroy
     @ticket = @event.tickets.find(params[:id])
     @ticket.destroy

     redirect_to admin_event_tickets_path(@event)
   end

   protected

   def find_event
     @event = Event.find_by_friendly_id!(params[:event_id])
   end

   def ticket_params
     params.require(:ticket).permit(:name, :description)
   end
end

app/helpers/admin/event_tickets_helper.rb
module Admin::EventTicketsHelper
end

app/views/admin/event_tickets/_form.html.erb
<% if @ticket.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @ticket.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :"业务名称" %>
  <%= f.text_field :name, :class => "form-control" %>
</div>


<div class="form-group">
  <%= f.label :"描述" %>
  <%= f.text_area :description, :class => "form-control" %>
</div>

app/views/admin/event_tickets/edit.html.erb
<h1>修改业务</h1>

<%= form_for [:admin, @event, @ticket] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Update", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_event_tickets_path(@event) %>
  </div>

<% end %>

app/views/admin/event_tickets/index.html.erb
<h1><%= @event.name %> / 业务列表</h1>

<p class="text-right">
<%= link_to "新业务", new_admin_event_ticket_path(@event), :class => "btn btn-primary" %>
</p>

<table class="table">
<tr>
  <th>业务名称</th>
  <th>描述</th>
  <th>操作</th>
</tr>
<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.name %></td>
    <td><%= simple_format ticket.description %></td>
    <td>
      <%= link_to "Edit", edit_admin_event_ticket_path(@event, ticket), :class => "btn btn-default" %>
      <%= link_to "Delete", admin_event_ticket_path(@event, ticket), :method => "delete", :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger" %>
  </tr>
<% end %>
</table>

app/views/admin/event_tickets/new.html.erb
<h1>新业务</h1>

<%= form_for [:admin, @event, @ticket] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Create", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_event_tickets_path(@event) %>
  </div>
<% end %>