config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  resources :events do
    resources :registrations do
      member do
        get "steps/1" => "registrations#step1", :as => :step1
        patch "steps/1/update" => "registrations#step1_update", :as => :update_step1
        get "steps/2" => "registrations#step2", :as => :step2
        patch "steps/2/update" => "registrations#step2_update", :as => :update_step2
        get "steps/3" => "registrations#step3", :as => :step3
        patch "steps/3/update" => "registrations#step3_update", :as => :update_step3
      end
    end
  end

  namespace :admin do
    root "events#index"
    resources :events do
      resources :tickets, :controller => "event_tickets"
      resources :departments, :controller => "event_departments"
      resources :jobs, :controller => "event_jobs"
      resources :registrations, :controller => "event_registrations"
    end
    resources :users
    resources :groups
  end

  resource :user
end

app/controllers/admin/event_departments_controller.rb
class Admin::EventDepartmentsController < ApplicationController
  layout "admin"

  before_action :find_event

   def index
     @departments = @event.departments
   end

   def new
     @department = @event.departments.new
   end

   def create
     @department = @event.departments.new(department_params)
     if @department.save
       redirect_to admin_event_departments_path(@event)
     else
       render "new"
     end
   end

   def edit
     @department = @event.departments.find(params[:id])
   end

   def update
     @department = @event.departments.find(params[:id])

     if @department.update(department_params)
       redirect_to admin_event_departments_path(@event)
     else
       render "edit"
     end
   end

   def destroy
     @department = @event.departments.find(params[:id])
     @department.destroy

     redirect_to admin_event_departments_path(@event)
   end

   protected

   def find_event
     @event = Event.find_by_friendly_id!(params[:event_id])
   end

   def department_params
     params.require(:department).permit(:name, :description)
   end
end

app/helpers/admin/event_departments_helper.rb
module Admin::EventDepartmentsHelper
end

app/views/admin/event_departments/_form.html.erb
<% if @department.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @ticket.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :"用户单位" %>
  <%= f.text_field :name, :class => "form-control" %>
</div>

app/views/admin/event_departments/edit.html.erb
<h1>修改用户单位</h1>

<%= form_for [:admin, @event, @department] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Update", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_event_departments_path(@event) %>
  </div>

<% end %>

app/views/admin/event_departments/index.html.erb
<h1><%= @event.name %> / 用户单位</h1>

<p class="text-right">
<%= link_to "新增用户单位", new_admin_event_department_path(@event), :class => "btn btn-primary" %>
</p>

<table class="table">
<tr>
  <th>用户单位名称</th>
  <th>操作</th>
</tr>
<% @departments.each do |department| %>
  <tr>
    <td><%= department.name %></td>
    <td>
      <%= link_to "Edit", edit_admin_event_department_path(@event, department), :class => "btn btn-default" %>
      <%= link_to "Delete", admin_event_department_path(@event, department), :method => "delete", :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger" %>
  </tr>
<% end %>
</table>

app/views/admin/event_departments/new.html.erb
<h1>新增用户单位</h1>

<%= form_for [:admin, @event, @department] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Create", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_event_departments_path(@event) %>
  </div>
<% end %>