config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  resources :events do
    resources :registrations do
      member do
        get "steps/1" => "registrations#step1", :as => :step1
        patch "steps/1/update" => "registrations#step1_update", :as => :update_step1
        get "steps/2" => "registrations#step2", :as => :step2
        patch "steps/2/update" => "registrations#step2_update", :as => :update_step2
        get "steps/3" => "registrations#step3", :as => :step3
        patch "steps/3/update" => "registrations#step3_update", :as => :update_step3
      end
    end
  end

  namespace :admin do
    root "events#index"
    resources :events do
      resources :tickets, :controller => "event_tickets"
      resources :departments, :controller => "event_departments"
      resources :jobs, :controller => "event_jobs"
      resources :registrations, :controller => "event_registrations"
    end
    resources :users
    resources :groups
  end

  resource :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  validates_presence_of :name
  belongs_to :event
  has_many :registrations
end

app/models/event.rb
class Event < ApplicationRecord

  validates_presence_of :name

  before_validation :generate_friendly_id, :on => :create

  has_many :tickets, :dependent => :destroy
  has_many :departments, :dependent => :destroy
  has_many :jobs, :dependent => :destroy
  has_many :registrations, :dependent => :destroy


  def to_param
    self.friendly_id
  end

  protected

  def generate_friendly_id
    self.friendly_id ||= SecureRandom.uuid
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships
  has_many :users, :through => :memberships
end

app/models/job.rb
class Job < ApplicationRecord
  validates_presence_of :name
  belongs_to :event
  has_many :registrations
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/registration.rb
class Registration < ApplicationRecord

  STATUS = ["pending", "confirmed"]
  validates_inclusion_of :status, :in => STATUS
  validates_presence_of :status, :ticket_id, :department_id, :job_id

  attr_accessor :current_step
  validates_presence_of :name, :if => :should_validate_basic_data?
  validates_presence_of :name, :if => :should_validate_all_data?

  belongs_to :event
  belongs_to :ticket
  belongs_to :department
  belongs_to :job

  belongs_to :user, :optional => true

  before_validation :generate_uuid, :on => :create

  scope :by_status, ->(s){ where( :status => s ) }
  scope :by_ticket, ->(t){ where( :ticket_id => t ) }
  scope :by_department, ->(d){ where( :department_id => d ) }
  scope :by_job, ->(j){ where( :job_id => j ) }

  def to_param
    self.uuid
  end

  protected

  def generate_uuid
    self.uuid = SecureRandom.uuid
  end

  def should_validate_basic_data?
    current_step == 2  # 只有做到第二步需要验证
  end

  def should_validate_all_data?
    current_step == 3 || status == "confirmed"  # 做到第三步，或最后状态是 confirmed 时需要验证
  end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates_presence_of :name
  belongs_to :event
  has_many :registrations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def display_name
    self.email.split("@").first
  end
  has_many :memberships
  has_many :groups, :through => :memberships
  has_many :registrations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_timezone
  
  def set_timezone
    if current_user && current_user.time_zone
      Time.zone = current_user.time_zone
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find_by_friendly_id!(params[:id])
    @registrations = @event.registrations.includes(:ticket, :department, :job).order("id DESC").page(params[:page]).per(10)

    if Array(params[:statuses]).any?
      @registrations = @registrations.by_status(params[:statuses])
    end

    if Array(params[:ticket_ids]).any?
      @registrations = @registrations.by_ticket(params[:ticket_ids])
    end

    if Array(params[:job_ids]).any?
      @registrations = @registrations.by_job(params[:job_ids])
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :find_event

  def new
  end

  def create
    @registration = @event.registrations.new(registration_params)
    @registration.ticket = @event.tickets.find( params[:registration][:ticket_id] )
    @registration.department = @event.departments.find( params[:registration][:department_id] )
    @registration.job = @event.jobs.find( params[:registration][:job_id] )
    @registration.status = "pending"
    @registration.user = current_user
    @registration.current_step = 1

    if @registration.save
      redirect_to step2_event_registration_path(@event, @registration)
    else
      render "new"
    end
  end

  def step1
    @registration = @event.registrations.find_by_uuid(params[:id])
  end

  def step1_update
    @registration = @event.registrations.find_by_uuid(params[:id])
    @registration.current_step = 1

    if @registration.update(registration_params)
      redirect_to step2_event_registration_path(@event, @registration)
    else
      render "step1"
    end
  end

  def step2
    @registration = @event.registrations.find_by_uuid(params[:id])
  end

  def step2_update
    @registration = @event.registrations.find_by_uuid(params[:id])
    @registration.current_step = 2

    if @registration.update(registration_params)
      redirect_to step3_event_registration_path(@event, @registration)
    else
      render "step2"
    end
  end

  def step3
    @registration = @event.registrations.find_by_uuid(params[:id])
  end

  def step3_update
    @registration = @event.registrations.find_by_uuid(params[:id])
    @registration.status = "confirmed"
    @registration.current_step = 3
    
    if @registration.update(registration_params)
      flash[:notice] = "日志更新成功"
      redirect_to event_registration_path(@event, @registration)
    else
      render "step3"
    end
  end

  def show
    @registration = @event.registrations.find_by_uuid(params[:id])
  end

  protected

  def registration_params
    params.require(:registration).permit(:ticket_id, :name, :email, :cellphone, :department_id, :job_id, :description)
  end

  def find_event
    @event = Event.find_by_friendly_id(params[:event_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      flash[:notice] = "修改成功"
      redirect_to edit_user_path
    else
      render "edit"
    end
  end

  protected

  def user_params
    params.require(:user).permit(:time_zone)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EagleDevelopment2</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/admin/">日志管理系统 后台</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li class="active"><%= link_to('部门管理', admin_events_path) %></li>
              <li><%= link_to('用户管理', admin_users_path) %></li>
              
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span> <%= current_user.display_name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "回到前台", root_path %></li>
                  <li><%= link_to('修改密碼', edit_registration_path(:user)) %></li>
                  <li><%= link_to('登出', destroy_user_session_path, :method => :delete) %></li>
                </ul>
              </li>
            <% else %>
            <li><%= link_to("注册", new_user_registration_path) %> </li>
            <li><%= link_to("登入", new_user_session_path) %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container" style="padding-top: 60px">

      <% if notice %>
        <p class="notice alert-success"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EagleDevelopment2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<div class="container">
  <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <a class="navbar-brand" href="/">xxxx</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <% if current_user %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                      <span class="glyphicon glyphicon-user"></span>
                      <%= current_user.display_name %>
                      <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu">
                      <li><%= link_to('管理員面板', admin_events_path) %></li>
                      <li><%= link_to('修改个人资料', edit_user_path) %></li>

                      <li><%= link_to('登出', destroy_user_session_path, :method => :delete) %></li>
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to("登入", new_user_session_path) %></li>
                <% end %>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
  </nav>
</div>
  <div class="container" style="padding-top: 60px">

    <% if notice %>
      <p class="notice alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
    </div>
  </body>
  <footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 xxx
        <br>Design by xxx

    </p>
</footer>
</html>